spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/h2_smlab_quiz_rest_api;AUTO_SERVER=TRUE
    username: localhost
    password: localhostuserpassword
    driver-class-name: org.h2.Driver
