spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/h2_jpoint2019;AUTO_SERVER=TRUE
    username: jpoint2019
    password: jpoint2019password
    driver-class-name: org.h2.Driver
